wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.11
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.9.7
    start_time: 1648784658
    t:
      1:
      - 1
      - 5
      - 41
      2:
      - 1
      - 5
      - 41
      3:
      - 2
      - 13
      - 16
      4: 3.9.7
      5: 0.12.11
      8:
      - 1
      - 5
architecture:
  desc: null
  value: GATConvGNN
dataset:
  desc: null
  value: GRSCD
epochs:
  desc: null
  value: 30
learning_rate:
  desc: null
  value: 0.0001
loss:
  desc: null
  value: LogeLoss
optim:
  desc: null
  value: SGD
