wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.11
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.9.7
    start_time: 1648837751
    t:
      1:
      - 1
      - 5
      - 41
      2:
      - 1
      - 5
      - 41
      3:
      - 2
      4: 3.9.7
      5: 0.12.11
      8:
      - 1
      - 5
    visualize:
      conf_mat:
        panel_config:
          fieldSettings:
            Actual: Actual
            Predicted: Predicted
            nPredictions: nPredictions
          panelDefId: wandb/confusion_matrix/v1
          stringSettings:
            title: ''
          transform:
            name: tableWithLeafColNames
          userQuery:
            queryFields:
            - args:
              - name: runSets
                value: ${runSets}
              fields:
              - fields: []
                name: id
              - fields: []
                name: name
              - fields: []
                name: _defaultColorIndex
              - args:
                - name: tableKey
                  value: conf_mat_table
                fields: []
                name: summaryTable
              name: runSets
        panel_type: Vega2
batch_size:
  desc: null
  value: 16
classes:
  desc: null
  value:
  - 1_cumulus
  - 2_altocumulus
  - 3_cirrus
  - 4_clearsky
  - 5_stratocumulus
  - 6_cumulonimbus
  - 7_mixed
criterion:
  desc: null
  value: cross_entropy
device:
  desc: null
  value: cuda:2
epochs:
  desc: null
  value: 30
hidden_dim:
  desc: null
  value: 1024
learning_rate:
  desc: null
  value: 1.995173662361221e-05
num_heads:
  desc: null
  value: 1
num_hidden:
  desc: null
  value: 2
optimizer:
  desc: null
  value: sgd
similarity_threshold:
  desc: null
  value: 0.75
