wandb_version: 1

batch_size:
  value: 16
criterion:
  value: loge
device:
  value: cuda:2
epochs:
  value: 25
hidden_dim:
  value: 256
learning_rate:
  value: 2.0041349912259276e-05
num_heads:
  value: 2
num_hidden:
  value: 2
optimizer:
  value: adam
similarity_threshold:
  value: 0.75
