wandb_version: 1

batch_size:
  value: 25
criterion:
  value: loge
device:
  value: cuda:2
epochs:
  value: 25
hidden_dim:
  value: 512
learning_rate:
  value: 3.0236125085020263e-05
num_heads:
  value: 1
num_hidden:
  value: 3
optimizer:
  value: adam
similarity_threshold:
  value: 0.9
