wandb_version: 1

batch_size:
  value: 17
criterion:
  value: loge
device:
  value: cuda:2
epochs:
  value: 25
hidden_dim:
  value: 512
learning_rate:
  value: 5.6846545379717045e-05
num_heads:
  value: 1
num_hidden:
  value: 4
optimizer:
  value: nadam
similarity_threshold:
  value: 0.75
